README.md

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Changed Labs back

---

client/yarn.lock

added components based on views in wireframe mock up

added component folders from wireframe

---

client/now.json
client/package.json

Built out the configurable `now.json` file that instructs Now how to handle app in the build phase. Also included `now-build` script that will specify what command Now will run to build the app.

Marious davis

---

client/package.json
client/src/App.js
client/src/actions/index.js
client/src/dummy-display/userList.js
client/src/dummy-display/userListView.js
client/src/dummy-display/users.js
client/src/index.js
client/src/reducers/index.js
client/yarn.lock

Added redux dependencies and set up actions and reducers. Also added components to display dummy data. This data/components can be changed to display data form back-end. Its is essentially a just a placeholder.
- cd into client and run yarn start

Set up redux and added components to display dummy data

---

client/src/components/billing/billing.js

added some notes to the billing section

commented some elements needed for billing

---

client/src/components/profile/profile.js

Commented some key features we will be building on the user profile page

Comments highlighting some profile features to be built out

---

README.md

Added new section to README
Manual test

Added new section to README.md

---

client/src/components/settings/settings.js

Added some notes to the settings section

Added comments for settings

---

client/now.json
client/package.json
client/public/index.html
client/src/App.js
client/yarn.lock

Added Auth0 dependency. Settled env's for Auth0 integration. Auth0 form displays upon user click on Login.

Initial Auth0 integration

---

client/now.json
client/src/App.js
client/src/actions/index.js
client/src/auth/auth.js
client/src/dummy-display/userList.js
client/src/dummy-display/users.js

Added necessary logic and checks to finish the login process for the react app and display feedback to the user by telling them their full name, letting them know that the Auth0 process completed successfully and that their user information is available to us for use.

Auth0 login function

---

client/src/App.css
client/src/App.js
client/src/actions/index.js

App displays data from back-end

---

client/src/App.js
client/src/components/button/slackButton.js
client/yarn.lock

added a slack button and extracted it to its own component.  button will be used communicate with slack and aide in the building of our slackusers db

added a slack button

---

client/src/components/button/slackButton.js

added webhooks into slack button so that we can receive the 'channel_id'

added webhooks to slack button

---

client/now.json
client/src/App.js
client/src/components/authentication/authentication.js
client/src/components/login/login.js
client/src/components/profile/profile.js

This change sets up an Authentication HOC that will conditionally render components based on logged-in status

Front-end conditional rendering

---

client/src/components/button/slackButton.js

removed webhooks

---

client/src/App.js

Display the users for the back-end

Adding User list to display

---

client/package.json
client/public/index.html
client/src/App.js
client/src/auth/auth.js
client/src/components/billing/billing.js
client/yarn.lock

build(core): installed front-end stripe dependencies and tested stripe customer creation/purchase

Stripe Front-end Integration

---

client/src/components/billing/billing.js

- fix(core): added Stripe API endpoints to correct front-end deployment
- fix(core): added `email` field to StripeCheckout for capturing user email dynamically

Fixing core Stripe functionality

---

client/src/components/billing/billing.js

Added in the url for local testing

Commented url for local testing

---

client/src/App.js
client/src/components/billing/premiumView.js

It isn't working like it should. Will try to fix it.
Added a status for premium users but doesn't quite work the way it should and doesn't break anything. I will need to work on it more.

added status for premium member

---

client/src/components/billing/billing.js

Corrects incorrect information listed in billing.js

Update subscription feature list in billing.js

---

client/src/App.js

removed premiumview, it is not ready just yet

removed premiumview

---

client/package.json
client/src/App.css
client/src/App.js
client/src/actions/index.js
client/src/components/billing/billing.js
client/src/components/profile/profile.js
client/src/reducers/index.js
client/yarn.lock

Changes layout of app and adds functionality to the focus, short, and long buttons

Steven oneill 9

---

client/src/App.js
client/src/components/login/login.js

Got auto fill for modal to work

Auto fill for modal works

---

client/src/App.css
client/src/App.js
client/src/actions/index.js
client/src/components/account_settings/account_settings.js
client/src/reducers/index.js

Added to the account settings and made mobile view

Added mobile view and added to the account settings page

---

client/src/App.css
client/src/actions/index.js
client/src/components/button/slackButton.js
client/src/components/profile/profile.js

updated code and edited the mobile view 

updated code

---

client/src/components/button/slackButton.js

updated slack button permissions

updated slack button permissions

---

client/src/actions/index.js
client/src/components/profile/profile.js
client/src/reducers/index.js

changed stop time function

---

client/src/App.js
client/src/components/button/slackButton.js

Fixed modal reload issue and added permissions to slack button

Fixed modal reload issue and added permissions to slack button

---

client/src/App.css
client/src/components/login/login.js
client/src/components/profile/profile.js

Added the customization for time

Customize time 

---

client/package.json
client/src/components/landing/landing.js
client/src/components/login/login.js
client/yarn.lock

Front-End PR for our initial Landing Page layout. Includes image placeholder for product demonstration GIF, product blurb, and comparison cards for free vs paid service.

Initial Landing Page Styling

---

client/src/components/login/login.js

Fixed bug issue with duplicate `Auth0Lock` import statements. Slight changes made to Landing Page comparison cards as well.

Light Bug Fix

---

client/src/App.js

added condition to submit for adding a user

Sean flannigan adduser

---

client/src/App.css
client/src/components/account_settings/account_settings.js
client/src/components/profile/profile.js

Css changes to profile and account settings

Css changes to profile and account settings

---

client/src/components/account_settings/account_settings.js

Fixed billing render issue

---

client/src/App.js

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

updated incorrect address

---

client/src/components/login/login.js

customized auth0 login

---

client/package.json
client/src/App.css
client/src/App.js
client/src/components/account_settings/account_settings.js
client/src/components/profile/profile.js

Enabled conditional render for custom time for premium user

Enabled conditional render for custom time for premium user

---

client/src/App.css
client/src/App.js
client/src/components/account_settings/account_settings.js
client/src/components/profile/profile.js

Added some conditional rendering and fixed some conditional rendering issues

Added some conditional rendering and fixed some conditional rendering issues

---

client/src/components/profile/profile.js

Fixed NaN issue for timer display

Fixed NaN issue for timer display

---

README.md

finished some of ReadMe, still needs work

finished some of ReadMe, still needs work

---

client/src/App.css
client/src/App.js
client/src/components/account_settings/account_settings.js
client/src/components/login/login.js
client/src/components/profile/profile.js

Fixed some render issues and made some changes from feedback

 Fixed some render issues and made some changes from feedback

---

client/src/App.js
client/src/components/account_settings/account_settings.css
client/src/components/account_settings/account_settings.js
client/src/components/settings/settings.js

moved logout to account settings page per feedback

moved logout to accounts page

---

client/src/components/account_settings/account_settings.css
client/src/components/account_settings/account_settings.js

fixed a routing issue with the logout.  logout should now route to the landing page

fixed routing on logout

---

client/src/components/account_settings/account_settings.js

Another quick fix to the logout

Another quick fix to the logout

---

client/src/App.js

Fixed the modal refresh issue
